Task1
MaksRoma/csdt2024ki47maksymiukrv12 pull request #1
Opened 2023-10-12 13:10 UTC by MaksRoma

Updated README file

2023-10-17 17:33 UTC, andrii-s-spitzer-lpnu-ua requested changes

2023-10-17 17:33 UTC, andrii-s-spitzer-lpnu-ua commented on README.md
> +Hardware: CY8CKIT-042 PSoC® 4 Pioneer Kit;
please add info about game and file format.

2023-10-17 17:33 UTC, andrii-s-spitzer-lpnu-ua commented on README.md
> +# Checkers game using PSoC4
rename main branch to develop

2023-10-17 21:04 UTC, MaksRoma commented
I don't know if any new changes are being pulled for this request, but I fixed what you asked for. Let me tell if you don't see any changes

2023-10-18 10:39 UTC, andrii-s-spitzer-lpnu-ua approved these changes

2023-10-18 10:46 UTC, merged